///
/// @Generated by Mockolo
///



import UIKit


public final class WebViewBuildableMock: WebViewBuildable {
    public init() { }


    public private(set) var buildCallCount = 0
    public var buildHandler: ((URL, WebViewListener) -> UIViewController)?
    public func build(url: URL, listener: WebViewListener) -> UIViewController {
        buildCallCount += 1
        if let buildHandler = buildHandler {
            return buildHandler(url, listener)
        }
        fatalError("buildHandler returns can't have a default value thus its handler must be set")
    }
}

public final class WebViewListenerMock: WebViewListener {
    public init() { }


    public private(set) var webViewDidCloseCallCount = 0
    public var webViewDidCloseHandler: (() -> ())?
    public func webViewDidClose() {
        webViewDidCloseCallCount += 1
        if let webViewDidCloseHandler = webViewDidCloseHandler {
            webViewDidCloseHandler()
        }
        
    }
}



