///
/// @Generated by Mockolo
///



import UIKit


public final class SearchBuildableMock: SearchBuildable {
    public init() { }


    public private(set) var buildCallCount = 0
    public var buildHandler: ((SearchListener) -> UIViewController)?
    public func build(listener: SearchListener) -> UIViewController {
        buildCallCount += 1
        if let buildHandler = buildHandler {
            return buildHandler(listener)
        }
        fatalError("buildHandler returns can't have a default value thus its handler must be set")
    }
}

public final class SearchListenerMock: SearchListener {
    public init() { }


}



