///
/// @Generated by Mockolo
///



import Entity
import Foundation


public final class RecentSearchesUseCaseMock: RecentSearchesUseCase, @unchecked Sendable {
    public init() { }


    private let fetchAllState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async throws -> [RecentSearchEntity]>())
    public var fetchAllCallCount: Int {
        return fetchAllState.withLock(\.callCount)
    }
    public var fetchAllHandler: (@Sendable () async throws -> [RecentSearchEntity])? {
        get { fetchAllState.withLock(\.handler) }
        set { fetchAllState.withLock { $0.handler = newValue } }
    }
    public func fetchAll() async throws -> [RecentSearchEntity] {
        let fetchAllHandler = fetchAllState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let fetchAllHandler = fetchAllHandler {
            return try await fetchAllHandler()
        }
        return [RecentSearchEntity]()
    }

    private let saveState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String) async throws -> ()>())
    public var saveCallCount: Int {
        return saveState.withLock(\.callCount)
    }
    public var saveHandler: (@Sendable (String) async throws -> ())? {
        get { saveState.withLock(\.handler) }
        set { saveState.withLock { $0.handler = newValue } }
    }
    public func save(keyword: String) async throws {
        let saveHandler = saveState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let saveHandler = saveHandler {
            try await saveHandler(keyword)
        }
        
    }

    private let deleteState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String) async throws -> ()>())
    public var deleteCallCount: Int {
        return deleteState.withLock(\.callCount)
    }
    public var deleteHandler: (@Sendable (String) async throws -> ())? {
        get { deleteState.withLock(\.handler) }
        set { deleteState.withLock { $0.handler = newValue } }
    }
    public func delete(keyword: String) async throws {
        let deleteHandler = deleteState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let deleteHandler = deleteHandler {
            try await deleteHandler(keyword)
        }
        
    }

    private let deleteAllState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async throws -> ()>())
    public var deleteAllCallCount: Int {
        return deleteAllState.withLock(\.callCount)
    }
    public var deleteAllHandler: (@Sendable () async throws -> ())? {
        get { deleteAllState.withLock(\.handler) }
        set { deleteAllState.withLock { $0.handler = newValue } }
    }
    public func deleteAll() async throws {
        let deleteAllHandler = deleteAllState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let deleteAllHandler = deleteAllHandler {
            try await deleteAllHandler()
        }
        
    }
}

public final class SearchRepositoriesUseCaseMock: SearchRepositoriesUseCase, @unchecked Sendable {
    public init() { }


    private let executeState = MockoloMutex(MockoloHandlerState<Never, @Sendable (String, Int) async throws -> (totalCount: Int, items: [RepositoryEntity])>())
    public var executeCallCount: Int {
        return executeState.withLock(\.callCount)
    }
    public var executeHandler: (@Sendable (String, Int) async throws -> (totalCount: Int, items: [RepositoryEntity]))? {
        get { executeState.withLock(\.handler) }
        set { executeState.withLock { $0.handler = newValue } }
    }
    public func execute(query: String, page: Int) async throws -> (totalCount: Int, items: [RepositoryEntity]) {
        let executeHandler = executeState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let executeHandler = executeHandler {
            return try await executeHandler(query, page)
        }
        return (0, [RepositoryEntity]())
    }
}

fileprivate func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
    print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

fileprivate func warnIfNotSendable<each T: Sendable>(function: String = #function, _: repeat each T) {
}

/// Will be replaced to `Synchronization.Mutex` in future.
fileprivate final class MockoloMutex<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Value
    init(_ initialValue: Value) {
        self.value = initialValue
    }
#if compiler(>=6.0)
    borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#else
    func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#endif
}

fileprivate struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
    var value: Value
    init(_ value: Value) {
        self.value = value
    }
}

fileprivate struct MockoloHandlerState<Arg, Handler> {
    var argValues: [MockoloUnsafeTransfer<Arg>] = []
    var handler: Handler? = nil
    var callCount: Int = 0
}

